# fly.toml app configuration file generated for joke-judge on 2023-07-18T20:59:35+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "joke-judge"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
